config/routes.rb
Rails.application.routes.draw do
  resources :elections

  resources :positions

  resources :districts

  resources :representatives

  resources :users

end

app/models/representative.rb
class Representative < ActiveRecord::Base

# has one position
# belongs to many users
# belongs to one district
# has many elections

end

app/controllers/representatives_controller.rb
class RepresentativesController < ApplicationController
  before_action :set_representative, only: [:show, :edit, :update, :destroy]

  # GET /representatives
  # GET /representatives.json
  def index
    @representatives = Representative.all
  end

  # GET /representatives/1
  # GET /representatives/1.json
  def show
  end

  # GET /representatives/new
  def new
    @representative = Representative.new
  end

  # GET /representatives/1/edit
  def edit
  end

  # POST /representatives
  # POST /representatives.json
  def create
    @representative = Representative.new(representative_params)

    respond_to do |format|
      if @representative.save
        format.html { redirect_to @representative, notice: 'Representative was successfully created.' }
        format.json { render :show, status: :created, location: @representative }
      else
        format.html { render :new }
        format.json { render json: @representative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /representatives/1
  # PATCH/PUT /representatives/1.json
  def update
    respond_to do |format|
      if @representative.update(representative_params)
        format.html { redirect_to @representative, notice: 'Representative was successfully updated.' }
        format.json { render :show, status: :ok, location: @representative }
      else
        format.html { render :edit }
        format.json { render json: @representative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /representatives/1
  # DELETE /representatives/1.json
  def destroy
    @representative.destroy
    respond_to do |format|
      format.html { redirect_to representatives_url, notice: 'Representative was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_representative
      @representative = Representative.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def representative_params
      params.require(:representative).permit(:first_name, :last_name, :office, :district_id, :phone, :email, :website)
    end
end

app/helpers/representatives_helper.rb
module RepresentativesHelper
end

app/views/representatives/_form.html.erb
<%= form_for(@representative) do |f| %>
  <% if @representative.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@representative.errors.count, "error") %> prohibited this representative from being saved:</h2>

      <ul>
      <% @representative.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :office %><br>
    <%= f.text_field :office %>
  </div>
  <div class="field">
    <%= f.label :district_id %><br>
    <%= f.text_field :district_id %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/representatives/edit.html.erb
<h1>Editing representative</h1>

<%= render 'form' %>

<%= link_to 'Show', @representative %> |
<%= link_to 'Back', representatives_path %>

app/views/representatives/index.html.erb
<h1>Listing representatives</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Office</th>
      <th>District</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @representatives.each do |representative| %>
      <tr>
        <td><%= representative.first_name %></td>
        <td><%= representative.last_name %></td>
        <td><%= representative.office %></td>
        <td><%= representative.district_id %></td>
        <td><%= representative.phone %></td>
        <td><%= representative.email %></td>
        <td><%= representative.website %></td>
        <td><%= link_to 'Show', representative %></td>
        <td><%= link_to 'Edit', edit_representative_path(representative) %></td>
        <td><%= link_to 'Destroy', representative, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Representative', new_representative_path %>

app/views/representatives/new.html.erb
<h1>New representative</h1>

<%= render 'form' %>

<%= link_to 'Back', representatives_path %>

app/views/representatives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @representative.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @representative.last_name %>
</p>

<p>
  <strong>Office:</strong>
  <%= @representative.office %>
</p>

<p>
  <strong>District:</strong>
  <%= @representative.district_id %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @representative.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @representative.email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @representative.website %>
</p>

<%= link_to 'Edit', edit_representative_path(@representative) %> |
<%= link_to 'Back', representatives_path %>